const router = require("express").Router()
const criar = require("../../Controller/UsuariosController/CriarUsuario")
const procurarUsuario = require("../../Controller/UsuariosController/ProcurarUsuario")
const procurarUsuarios = require("../../Controller/UsuariosController/ProcurarUsuarios")
const deletarUsuario = require("../../Controller/UsuariosController/Deletarusuario")
const actualizarUsuario = require("../../Controller/UsuariosController/ActualizarUsuario")
const login = require("../../Authentication/AuthLogin/login")
const autenticacao = require("../../Authentication/AuthMiddleware/auth")

router.route("/usuario/signup").post((req, res) => {criar.criarUsuario(req, res)})
router.route("/usuario/login").post((req, res) => {login.login(req, res)})
router.route("/usuario/apagar-conta/:id_usuario").delete((req, res) => {deletarUsuario.apagarUsuario(req, res)})
router.route("/usuario/actualizar-conta/:id_usuario").put((req, res) => {actualizarUsuario.actualizarUsuario(req, res)})
router.route("/usuario/:id_usuario").post((req, res) =>{procurarUsuario.ProcurarUsuario(req, res)})
router.route("/usuarios").get(autenticacao.Autenticacao, (req, res) => {procurarUsuarios.procurarUsuarios(req, res)})
module.exports = router
